name: ironmind # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.3.15' # just for humans, typically '1.2+git' or '1.3.2'
summary: Brainf*ck interpreter and code execution visualizer # 79 char long summary
description: |
  Built in Rust.
  Written by Jaden Arceneaux 

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
- build-on: amd64
- build-on: arm64
- build-on: armhf

parts:
  ironmind:
    build-packages:
      - libncurses5-dev
      - libncursesw5-dev
    source: https://github.com/Jadens-arc/Ironmind.git
    # See 'snapcraft plugins'
    plugin: rust

apps:
  ironmind:
    command: bin/ironmind
    plugs:
      - home
      - removable-media
      - desktop

  
